/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package htw.berlin.wi.prog2;

import htw.berlin.wi.prog2.service.SimpleInputParser;
import htw.berlin.wi.prog2.service.BowlBuilder;
import htw.berlin.wi.prog2.ui.CommandLineUI;
import htw.berlin.wi.prog2.ui.UserInputWrapper;

public class BowlBotApp {
    public static void main(String[] args) {
        SimpleInputParser parser = new SimpleInputParser();
        BowlBuilder builder = new BowlBuilder();
        CommandLineUI clui = new CommandLineUI(new UserInputWrapper(System.in, System.out), builder, parser);
        clui.launch();
    }
}
